---
- name: Launch EC2 instance
  hosts: localhost
  tasks:
    - name: Create a security group
      ec2_group:
        name: webserver_sg
        description: Security group for webserver
        region: us-east-1
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0

    - name: Launch instance
      ec2:
        key_name: mykey
        group: webserver_sg
        instance_type: t2.micro
        image: ami-0c55b159cbfafe1f0
        wait: yes
        region: us-east-1
        count: 1
        instance_tags:
          Name: WebServer
